-- LobeHub MCP Server - ANSI SQL Schema
-- Converted from Oracle SQL to ANSI SQL Standard
-- Compatible with most SQL databases following ANSI standards

-- Main MCP server table
CREATE TABLE mcp_server (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    author VARCHAR(255),
    development_language VARCHAR(100),
    license VARCHAR(255),
    download_count BIGINT DEFAULT 0 CHECK (download_count >= 0),
    overview CLOB,
    short_description VARCHAR(1000),
    server_slug VARCHAR(255) NOT NULL UNIQUE,
    lobehub_url VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_active SMALLINT DEFAULT 1 NOT NULL CHECK (is_active IN (0, 1)),
    CONSTRAINT chk_mcp_server_name_length CHECK (CHAR_LENGTH(TRIM(name)) > 0)
);

-- Links table for MCP server external links
CREATE TABLE mcp_server_links (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id INTEGER NOT NULL,
    link_type VARCHAR(100),
    is_primary SMALLINT DEFAULT 0 CHECK (is_primary IN (0, 1)),
    url VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_mcp_server_links FOREIGN KEY (mcp_server_id) REFERENCES mcp_server(id)
);

-- Dependencies table for MCP server requirements
CREATE TABLE mcp_server_dependencies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id INTEGER NOT NULL,
    dependency_type VARCHAR(100),
    dependency_name VARCHAR(255) NOT NULL,
    version_requirement VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_mcp_server_dependencies FOREIGN KEY (mcp_server_id) REFERENCES mcp_server(id)
);

-- Installation methods table for different platforms
CREATE TABLE mcp_server_installation_methods (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dependency_id INTEGER NOT NULL,
    platform VARCHAR(50) NOT NULL,
    installation_command VARCHAR(1000),
    installation_url VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_installation_dependency FOREIGN KEY (dependency_id) REFERENCES mcp_server_dependencies(id)
);

-- Tools table for MCP server available tools
CREATE TABLE mcp_server_tools (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id INTEGER NOT NULL,
    tool_name VARCHAR(255) NOT NULL,
    tool_description VARCHAR(1000),
    is_active SMALLINT DEFAULT 1 NOT NULL CHECK (is_active IN (0, 1)),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_mcp_server_tools FOREIGN KEY (mcp_server_id) REFERENCES mcp_server(id)
);

-- Tool parameters table for tool input specifications
CREATE TABLE mcp_server_tool_parameters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_id INTEGER NOT NULL,
    parameter_name VARCHAR(255) NOT NULL,
    parameter_type VARCHAR(100),
    is_required SMALLINT DEFAULT 0 CHECK (is_required IN (0, 1)),
    parameter_description VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_tool_parameters FOREIGN KEY (tool_id) REFERENCES mcp_server_tools(id)
);

-- Prompts table for MCP server configuration prompts
CREATE TABLE mcp_server_prompts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id INTEGER NOT NULL,
    prompt_name VARCHAR(255) NOT NULL,
    prompt_description VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_mcp_server_prompts FOREIGN KEY (mcp_server_id) REFERENCES mcp_server(id)
);

-- Prompt parameters table for prompt configuration options
CREATE TABLE mcp_server_prompt_parameters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_id INTEGER NOT NULL,
    parameter_name VARCHAR(255) NOT NULL,
    is_required SMALLINT DEFAULT 0 CHECK (is_required IN (0, 1)),
    parameter_description VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_prompt_parameters FOREIGN KEY (prompt_id) REFERENCES mcp_server_prompts(id)
);

-- Resources table for MCP server attached resources
CREATE TABLE mcp_server_resources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id INTEGER NOT NULL,
    resource_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(255),
    uri VARCHAR(1000) NOT NULL,
    resource_description VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_mcp_server_resources FOREIGN KEY (mcp_server_id) REFERENCES mcp_server(id)
);

-- Score table for MCP server quality assessment
CREATE TABLE mcp_server_scores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id INTEGER NOT NULL,
    overall_score SMALLINT NOT NULL,
    grade VARCHAR(2) NOT NULL,
    grade_percentage DECIMAL(5,2) NOT NULL,
    validation_status VARCHAR(50) DEFAULT 'Validated',
    installation_methods_count SMALLINT DEFAULT 0,
    tools_count SMALLINT DEFAULT 0,
    resources_count SMALLINT DEFAULT 0,
    has_readme SMALLINT DEFAULT 0 CHECK (has_readme IN (0, 1)),
    has_license SMALLINT DEFAULT 0 CHECK (has_license IN (0, 1)),
    has_prompts SMALLINT DEFAULT 0 CHECK (has_prompts IN (0, 1)),
    is_claimed_by_owner SMALLINT DEFAULT 0 CHECK (is_claimed_by_owner IN (0, 1)),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_mcp_server_scores FOREIGN KEY (mcp_server_id) REFERENCES mcp_server(id)
);

-- Score details table for individual scoring criteria
CREATE TABLE mcp_server_score_details (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    score_id INTEGER NOT NULL,
    criteria_name VARCHAR(255) NOT NULL,
    criteria_description VARCHAR(1000),
    is_met SMALLINT DEFAULT 0 CHECK (is_met IN (0, 1)),
    points_awarded SMALLINT DEFAULT 0 CHECK (points_awarded >= 0),
    max_points SMALLINT DEFAULT 0 CHECK (max_points >= 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_score_details FOREIGN KEY (score_id) REFERENCES mcp_server_scores(id)
);

-- MCP version history table to track version releases
CREATE TABLE mcp_version_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id INTEGER NOT NULL,
    version_number VARCHAR(20) NOT NULL,
    is_validated SMALLINT DEFAULT 0 CHECK (is_validated IN (0, 1)),
    published_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_server_version UNIQUE (mcp_server_id, version_number),
    CONSTRAINT fk_mcp_version_history FOREIGN KEY (mcp_server_id) REFERENCES mcp_server(id)
);

-- MCP related servers table to store relationships between servers
CREATE TABLE mcp_related_servers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id INTEGER NOT NULL,
    related_server_id INTEGER NOT NULL,
    relationship_type VARCHAR(100),
    description VARCHAR(1000),
    is_active SMALLINT DEFAULT 1 NOT NULL CHECK (is_active IN (0, 1)),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_server_relationship UNIQUE (mcp_server_id, related_server_id),
    CONSTRAINT fk_mcp_related_main FOREIGN KEY (mcp_server_id) REFERENCES mcp_server(id),
    CONSTRAINT fk_mcp_related_target FOREIGN KEY (related_server_id) REFERENCES mcp_server(id),
    CONSTRAINT chk_no_self_reference CHECK (mcp_server_id != related_server_id)
);
