-- LobeHub MCP Server - ANSI SQL Schema
-- Converted from Oracle SQL to ANSI SQL Standard
-- Compatible with most SQL databases following ANSI standards
-- NOTE: Added `mcp_directory_api VARCHAR(1000)` to `mcp_servers` on 2025-09-15 to store MCP directory API endpoint for Glama.ai

CREATE TABLE mcp_servers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    author VARCHAR(255),
    development_language VARCHAR(100),
    license VARCHAR(255),
    download_count BIGINT DEFAULT 0 CHECK (download_count >= 0),
    overview CLOB,
    short_description VARCHAR(1000),
    server_slug VARCHAR(255) NOT NULL UNIQUE,
    mcp_directory_api VARCHAR(1000),
    lobehub_url VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_active SMALLINT DEFAULT 1 NOT NULL CHECK (is_active IN (0, 1)),
        CONSTRAINT chk_mcp_server_name_length CHECK (CHAR_LENGTH(TRIM(name)) > 0)
);

-- Links table for MCP server external links
CREATE TABLE mcp_server_links (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id INTEGER NOT NULL,
    link_type VARCHAR(100),
    is_primary SMALLINT DEFAULT 0 CHECK (is_primary IN (0, 1)),
    url VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_mcp_server_links FOREIGN KEY (mcp_server_id) REFERENCES mcp_servers(id)
);

-- Dependencies table for MCP server requirements
CREATE TABLE mcp_server_dependencies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id INTEGER NOT NULL,
    dependency_type VARCHAR(100),
    dependency_name VARCHAR(255) NOT NULL,
    version_requirement VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_mcp_server_dependencies FOREIGN KEY (mcp_server_id) REFERENCES mcp_servers(id)
);

-- Installation methods table for different platforms
CREATE TABLE mcp_server_installation_methods (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dependency_id INTEGER NOT NULL,
    platform VARCHAR(50) NOT NULL,
    installation_command VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_installation_dependency FOREIGN KEY (dependency_id) REFERENCES mcp_server_dependencies(id)
);

-- Tools table for MCP server available tools
CREATE TABLE mcp_server_tools (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id INTEGER NOT NULL,
    tool_name VARCHAR(255) NOT NULL,
    tool_description VARCHAR(1000),
    is_active SMALLINT DEFAULT 1 NOT NULL CHECK (is_active IN (0, 1)),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_mcp_server_tools FOREIGN KEY (mcp_server_id) REFERENCES mcp_servers(id)
);

-- Tool parameters table for tool input specifications
CREATE TABLE mcp_server_tool_parameters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_id INTEGER NOT NULL,
    parameter_name VARCHAR(255) NOT NULL,
    parameter_type VARCHAR(100),
    is_required SMALLINT DEFAULT 0 CHECK (is_required IN (0, 1)),
    parameter_description VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_tool_parameters FOREIGN KEY (tool_id) REFERENCES mcp_server_tools(id)
);

-- Prompts table for MCP server configuration prompts
CREATE TABLE mcp_server_prompts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id INTEGER NOT NULL,
    prompt_name VARCHAR(255) NOT NULL,
    prompt_description VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_mcp_server_prompts FOREIGN KEY (mcp_server_id) REFERENCES mcp_servers(id)
);

-- Prompt parameters table for prompt configuration options
CREATE TABLE mcp_server_prompt_parameters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_id INTEGER NOT NULL,
    parameter_name VARCHAR(255) NOT NULL,
    is_required SMALLINT DEFAULT 0 CHECK (is_required IN (0, 1)),
    parameter_description VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_prompt_parameters FOREIGN KEY (prompt_id) REFERENCES mcp_server_prompts(id)
);

-- Resources table for MCP server attached resources
CREATE TABLE mcp_server_resources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id INTEGER NOT NULL,
    resource_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(255),
    uri VARCHAR(1000) NOT NULL,
    resource_description VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_mcp_server_resources FOREIGN KEY (mcp_server_id) REFERENCES mcp_servers(id)
);

-- Score table for MCP server quality assessment
CREATE TABLE mcp_server_scores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id INTEGER NOT NULL,
    -- Keep a small summary of scores and statuses as shown in Lobehub UI
    validation_status VARCHAR(50) DEFAULT 'Validated', -- "Validated" (This MCP Server has passed installation validation...)
    installation_methods_count SMALLINT DEFAULT 0, -- "Provides At Least One Installation Method" (number of installation methods)
    installation_methods_friendly SMALLINT DEFAULT 0 CHECK (installation_methods_friendly IN (0,1)), -- "Offers Friendly Installation Methods" (friendlier than Manual)
    tools_count SMALLINT DEFAULT 0 CHECK (tools_count >= 0), -- "Includes At Least One Tool" (number of tool features)
    has_readme SMALLINT DEFAULT 0 CHECK (has_readme IN (0, 1)), -- "Has README"
    has_license SMALLINT DEFAULT 0 CHECK (has_license IN (0, 1)), -- "Has LICENSE"
    includes_prompts SMALLINT DEFAULT 0 CHECK (includes_prompts IN (0,1)), -- "Includes Prompts"
    includes_resources SMALLINT DEFAULT 0 CHECK (includes_resources IN (0,1)), -- "Includes Resources"
    is_claimed_by_owner SMALLINT DEFAULT 0 CHECK (is_claimed_by_owner IN (0,1)), -- "Not Claimed by Owner" / claimed flag
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_mcp_server_scores FOREIGN KEY (mcp_server_id) REFERENCES mcp_servers(id)
);

-- MCP version history table to track version releases
CREATE TABLE mcp_version_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id INTEGER NOT NULL,
    version_number VARCHAR(20) NOT NULL,
    is_validated SMALLINT DEFAULT 0 CHECK (is_validated IN (0, 1)),
    published_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_server_version UNIQUE (mcp_server_id, version_number),
    CONSTRAINT fk_mcp_version_history FOREIGN KEY (mcp_server_id) REFERENCES mcp_servers(id)
);
